rvm:
  - 2.3.0
language: ruby
addons:
  postgresql: 9.4
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - psql -c 'create database catday_test;' -U postgres

script: xvfb-run bundle exec rspec
